blogposts/urls.py
from django.urls import path

from blogposts.apps import BlogpostsConfig
from blogposts.views import BlogpostCreateView, BlogpostListView, BlogpostDetailView, BlogpostUpdateView, \
    BlogpostDeleteView

app_name = BlogpostsConfig.name

urlpatterns = [
    path('create/', BlogpostCreateView.as_view(), name='create'),
    path('', BlogpostListView.as_view(), name='list'),
    path('view/<int:pk>', BlogpostDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogpostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogpostDeleteView.as_view(), name='delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogposts/', include('blogposts.urls', namespace='blogposts')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, VerifyView, UserUpdateView, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/<str:token>/', VerifyView.as_view(), name='verify'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogposts/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blogpost(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(**NULLABLE, max_length=200, verbose_name='slug')
    content = models.TextField(**NULLABLE, verbose_name='содержимое')
    preview = models.ImageField(upload_to='blogposts/', **NULLABLE, verbose_name='изображение (превью)')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title} {self.content}'

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

blogposts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.templatetags.pytils_translit import slugify

from blogposts.models import Blogpost


class BlogpostCreateView(LoginRequiredMixin, CreateView):
    model = Blogpost
    fields = ('title', 'content')
    success_url = reverse_lazy('blogposts:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogpostUpdateView(LoginRequiredMixin, UpdateView):
    model = Blogpost
    fields = ('title', 'content')
    success_url = reverse_lazy('blogposts:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogposts:view', args=[self.kwargs.get('pk')])


class BlogpostListView(ListView):
    model = Blogpost

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogpostDetailView(DetailView):
    model = Blogpost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogpostDeleteView(LoginRequiredMixin, DeleteView):
    model = Blogpost
    success_url = reverse_lazy('blogposts:list')

blogposts/templates/blogposts/blogpost_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить отзыв"{{object.title}}?"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blogposts:list'%}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogposts/templates/blogposts/blogpost_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">

            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Отзыв "{{ object.title }}" ({{ object.slug }})
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ object.content }}
                        </p>

                    </div>
                    <div class="card-footer">
                        Просмотры:{{ object.views_count }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogposts/templates/blogposts/blogpost_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogposts/templates/blogposts/blogpost_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-primary" href="{% url 'blogposts:create' %}">Добавить отзыв</a>
<div class="row">
    {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">{{ object.title|title }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blogposts:view' object.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                            <a href="{% url 'blogposts:edit' object.pk %}" type="button" class="btn btn-sm btn-outline-warning">Edit</a>
                            <a href="{% url 'blogposts:delete' object.pk %}" type="button" class="btn btn-sm btn-outline-danger">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}